"""init

Revision ID: 7f8fc4f133da
Revises: 
Create Date: 2026-03-25 12:57:03.053522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8fc4f133da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_materials_file_hash'), 'audio_materials', ['file_hash'], unique=True)
    op.create_index(op.f('ix_audio_materials_id'), 'audio_materials', ['id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['audio_materials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_id'), 'practice_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_material_id'), 'practice_sessions', ['material_id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_session_id'), 'practice_sessions', ['session_id'], unique=True)
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['audio_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'seq', name='uq_subtitle_material_seq')
    )
    op.create_index(op.f('ix_subtitles_id'), 'subtitles', ['id'], unique=False)
    op.create_index(op.f('ix_subtitles_material_id'), 'subtitles', ['material_id'], unique=False)
    op.create_table('sentence_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('subtitle_id', sa.Integer(), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_attempts_id'), 'sentence_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_sentence_attempts_session_id'), 'sentence_attempts', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentence_attempts_session_id'), table_name='sentence_attempts')
    op.drop_index(op.f('ix_sentence_attempts_id'), table_name='sentence_attempts')
    op.drop_table('sentence_attempts')
    op.drop_index(op.f('ix_subtitles_material_id'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_practice_sessions_session_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_material_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_audio_materials_id'), table_name='audio_materials')
    op.drop_index(op.f('ix_audio_materials_file_hash'), table_name='audio_materials')
    op.drop_table('audio_materials')
    # ### end Alembic commands ###
